[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
gas_reports = ["*"]
optimizer = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
